### PR TITLE
Improve routing for submission views with slug-like numbers

### PR DESCRIPTION
**Pull request by waxlamp**
TODO:
- [x] replace `meta.number` with `meta.submissionNumber` and `meta.revisionNumber`
- [x] implement a global counter to generate new submission numbers and local counters for revision numbers within a given submission, and use these to tag new submissions/revisions with numbers upon their creation

### CODE REVIEW

**Comment by waxlamp** [comment]
@josephsnyder this is now ready for review.

**Comment by waxlamp** [comment]
@josephsnyder in 3bd0eeb I fixed that "$ is not defined" issue, PTAL.

**Comment by josephsnyder** [comment]
The latest forcepush is a rebase to remove merge conflicts. All else looks good!

**Comment by waxlamp** [comment]
Fantastic! Thanks @josephsnyder!

**Pull request merged**
